<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SerenAuth.Infrastructure</RootNamespace>
    <AssemblyName>SerenAuth.Infrastructure</AssemblyName>
    <InternalsVisibleTo>SerenAuth.Domain</InternalsVisibleTo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SerenAuth.Domain\SerenAuth.Domain.csproj" />
    <ProjectReference Include="..\SerenAuth.Application\SerenAuth.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
  </ItemGroup>
</Project>
